def count_nucleotides_inDNA(DNA_string):

    adenine = 0
    cytosine = 0
    guanine = 0
    thymine = 0

    # for loop to iterate through DNA string
    for nt in DNA_string:
        if nt == "A":
            adenine = adenine + 1
        elif nt == "C":
            cytosine = cytosine + 1
        elif nt == "G":
            guanine = guanine + 1
        elif nt == "T":
            thymine = thymine + 1

    # present the numbers(ACGT) in a print statement seperated by spaces
    print(adenine,cytosine,guanine,thymine, sep=' ')

DNA_string = 'TCTCGTCGGATCCTCGTCCGCAGTCACCGCTGCTGGTCATGTTGGAACGATGGAGTTTGAGTTAGTACCTTGGGATACGATCCAGAACGTGACCCGCGGCGATATCACCACTTCAGCCTGGCGGTAGATCAACTTACGGCCTGTCGACGTGCGTTCACTCAGTGATACACGCATCAACGGGGCTTACCCGGGACCATGCTTGCGCAAGTTGCTCCTGACCGAATCCAAGAGCAGATGGAACTTGAAGGACAGCTCCCTTCCTCCGCCCCGGTTATTGGAAAGGGCAGTGGAACCGTCATGACTTTACACCTGTACATTTTACGGCCAGCCTGTAGTTGTTAGTCCCAGCAGCGTCCACGCCTCATTTGATCGCTGCAAGTGATTGAGAGGTACTGGATAGAGAGATTCCCATCGACCGTAGCGCACTTCTAAAGGGAAGGTTTGTTTTATGGCTACTACGCACACATCTCAGGGTATTCTTCTGCTGGGCCCGAGCATATGTCTTTGGTTTGCCTTTGCTCGCTCAAATTGTGGCCTGAATCAAGCCAATATACAATCTATAGCGGAAAAGTTGAGCCCACCCTTGACATATAACCCATAGACTGGTACCGTAGAATACATATCGGAGGGAAGTCAAGATAACATTCGCCGCCACTCTTGATCAGGAGAATGAGCATCCTGGACTCATATACAGAAATGTGAGTCGCCGCGTGTGAATATTTCCCCGCGCTCCTACGCGTGAGCTACGGATGCGTATCCATATCTCTGACTACGGCCATAGTCTGGGGAAGGGCCTTCCCGAGACTACGTTCTGGAATTGTGATACTTCGTCCGACGCGAATTTTTGTTAGCTGACTGGCATCCAGAAAAACCTTTCTTCTGAGGGCCGCAGGTCCTTACACGGCAGACATGGCTCGT'
count_nucleotides_inDNA(DNA_string)

