def DNA_complement(DNA_given):
    #DNA_given  first given strand of DNA
    DNA_compl = '' # not reversed!!! the second strand of DNA which we recieve from given one
    DNA_complem = ''
    #replace nucliotides adenine A with thymine T, cytisine C with guanine G and vice verse
    for nt in DNA_given:
        if nt == 'A': 
            DNA_compl = DNA_compl + 'T'
            
        elif nt == 'T':
            DNA_compl = DNA_compl + 'A'
            
        elif nt == 'C':
            DNA_compl = DNA_compl +'G'
            
        elif nt == 'G':
            DNA_compl = DNA_compl + 'C'   

    #reverse the string 
    for nt in DNA_compl:
        DNA_complem = nt + DNA_complem
  

    #print(DNA_compl)
    print(DNA_complem)
    return DNA_complem

DNA_complement('TTCCCTGCGCGCCAACCCCCTACGGCGTAGTTCAGCACTTGTTCCGTACTGTCAACAGCGACCTCCCTTTATCACCCAACACTTATCTTAAAACTCTACCTGCCATTAGAACTAAAATGGAGCGCAGTGTTAGCGGGACGCCTTGATCTTTTACACGACGTGTGGACCCCGGCGGCTGAGATATACTTACATTTTTGGATACACACCGGTTTCTCACCACGGTTAATAAAGTCGAGCATACCCCCGACTAGTTGTGGTCGTGCAGAAACGTTGCATAGACCTCACCTGCTACGAGCGAGCCCCAGTTGCCGACAACCAAGGTCGGGCTTAATGGGTTGTGAAGCATGAAAGAATATTTGGAAGGTAACGACAAAGACCGAGTAGACGAGATAAACCATGGTTGGCCCACTGGTAGTTTAGCAGATACAACTTAATTCCGGAACCCATGGACGCACGAGATGTTATCCAAGTATCATGTACATTATCAGAACACATATTTCTACAGAAACACTGCGGTACGGCGAACCGTATTTTGTCATAAGAGGTTCCTGCTTGAGAACCCATGTTACGCGGCTCCCACATAAAGTCATATATCTTTCGTTGGCGCGAGGGATGACGGGTTAGGACCATCGGCGGAAAAATTACACTCTTATTTAGGTGGGTGGTGGTTGGGTTTATTCAAGGCTGTGAGGTCTATTGGGGTAATTTACCGTGCCGTTCCTTCTGGAGACTTCCTGTCCCGATCGCTACGTAGCTATACCGGCTTTCGCCCTTGCCATTACAGTAGCTCCACTGTCACAGCTAAGTTGTAGGCACTACCGCACCTGTTACAGTCGGGCCGCAGTTAACCTTGTGGGACAAACCTAGTGTATTTAAAGGACGTGGG')
