
def DNA_in_RNA(DNA_str):
    RNA_str = ''

    for nt in DNA_str:
        if nt == 'T':
            RNA_str = RNA_str + 'U' #Uracil instead of thymine
        else:
            RNA_str = RNA_str + nt  # adenine, cytosine, guanine stays on their places 

    print(RNA_str)

DNA_str = 'GTAGTCCCGTTTGGACTTAGAGTCCAATACGAACTCAACTGGAATAATATTATAACGTCCGGTAGTCCCGTATAGCCTACATCTGGCTGTCCAACTGATATCCCCTAATGCGTGGGATCGAAGCGGCTTAAGCACCCACATGCGCGCTTAGCATAGAAAGATTCTGTCCACGTGAACTATATAGCGAAAGCCCGGGGGCCAAGCTTAGATTCGGAACAATGCCAGAAAAGATGCCTTCTATGAGTGCTCCAGGGTCGACACTCAGCGAATCTCCGACTTAAGTCGTTCCCAGGCAGGCAGTTCGTGTTTGAAACCAGGAGGATCATGGTTATTCTGGTAGTGTTAAGGCCGTAAACCAACGGCGCAGACTGGCTAGTCTATCCGAGATATGAAGTGTCTCTCCGCAAATTCTAATGATCAACCGGGGGGCTTTGGTGTCATTCCTTACAGGTTACTGAGGTCCGGCGACTTGCCCTTGAACCTATTGGGTACGACAAGCGACTTCTTTGTTAATCGCTGAGCAGGGCGTAGAGAGTGACGCCCCAGGGAACCCCATGCCAATTCGCCTTCTGGTAGCACCAGCATAATCGCGCTCCTAGTACGTGGCGTTCGAATATTGGCAGGTAGGCCGCGGAACCTGGATACGGCCAATCAGTGCTCCTTACGAATTCTAACCGCTGTACTAGATATGTACAATGGGTCGAGCCTAGTACACGTCCTGTGCCCGATATGCAATGCACACCCCGTCCTTCCCCCCCTAGCCTGGCGACTCAGCTAGGGGCTGGCTCCCAACTAGGGGAACAGTTGCCGACACGCTAAACCTAAGGGTGCGTGGCTTTCTGCGGACACTGTCGATCCCCCGCGCGGTATCGCATAGGGCGACCTCGCGAACGAAATCTTCACCAAGTATGCAGAGCCCCCTTATTCTTCTAGCTGACTAGCCATGAAGCACCATGAGTCACTGG'
DNA_in_RNA(DNA_str)